import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const dictionary = {
    en: {
        // Accessibility / General Widget
        "Acessibilidade": "Accessibility",
        "Zoom do Texto": "Text Zoom",
        "Diminuir Fonte": "Zoom Out",
        "Resetar Fonte": "Reset Zoom",
        "Aumentar Fonte": "Zoom In",
        "Fonte Alternativa": "Alternative Font",
        "Alto Contraste": "High Contrast",
        "Leitor por Voz (Hover)": "Screen Reader (Hover)",
        "Ativado": "Enabled",
        "Desativado": "Disabled",
        "Ligado": "On",
        "Desligado": "Off",
        "Idioma / Language": "Language",
        "Mudar para Tema Escuro": "Switch to Dark Theme",
        "Mudar para Tema Claro": "Switch to Light Theme",
        "Opções de Acessibilidade": "Accessibility Options",

        // Sidebar
        "Timer": "Timer",
        "Tarefas": "Tasks",
        "Histórico": "History",
        "Calendário": "Calendar",
        "Dashboard": "Dashboard",
        "Usuários": "Users",
        "Configurações": "Settings",
        "Suporte": "Support",
        "Admin": "Admin",
        "Sair": "Logout",
        "Voltar ao App": "Back to App",

        // TimerWidget
        "No que você está trabalhando?": "What are you working on?",
        "Começar": "Start",
        "Parar": "Stop",
        "Hoje": "Today",
        "Ontem": "Yesterday",
        "Sem Projeto": "No Project",
        "Sem notas": "No notes",
        "Tempo Total": "Total Time",
        "Categoria": "Category",
        "Observações...": "Notes...",

        // TaskSelectorPanel / Timer Page
        "Opções do Timer": "Timer Options",
        "A fazer...": "To do...",
        "Buscar tarefa...": "Search task...",
        "Nenhum projeto encontrado. Vá para a página de tarefas para criar um.": "No projects found. Go to the tasks page to create one.",
        "Criando tarefa...": "Creating task...",
        "Nova Task": "New Task",

        // TasksPage & TaskManagerBoard
        "Gerenciamento de Projetos e Tarefas": "Project & Task Management",
        "Nova Categoria": "New Category",
        "Nome da Categoria": "Category Name",
        "Criar Categoria": "Create Category",
        "Novo Projeto": "New Project",
        "Nome do Projeto": "Project Name",
        "Criar Projeto": "Create Project",
        "Nome da Tarefa": "Task Name",
        "Selecione uma Categoria": "Select a Category",
        "Selecione o Projeto": "Select Project",
        "Valor/Hora": "Rate/Hour",
        "Horas Orçadas": "Budgeted Hours",
        "Criar Tarefa": "Create Task",
        "Minimizar projeto": "Collapse project",
        "Expandir projeto": "Expand project",
        "Editar Projeto": "Edit Project",
        "Excluir Projeto": "Delete Project",
        "Anexar arquivo na nuvem": "Attach cloud file",
        "Anexar arquivo": "Attach file",
        "Nenhum projeto foi criado ainda.": "No projects have been created yet.",
        "Nenhuma tarefa cadastrada para este projeto.": "No tasks registered for this project.",
        "Arquivos Anexados": "Attached Files",
        "Download": "Download",
        "Deseja realmente excluir este projeto? Todas as tarefas associadas serão apagadas permanentemente.": "Are you sure you want to delete this project? All associated tasks will be permanently deleted.",
        "Confirmar Exclusão": "Confirm Deletion",
        "Deseja excluir este projeto e todas as suas tarefas?": "Do you want to delete this project and all its tasks?",
        "Excluir": "Delete",
        "Cancelar": "Cancel",
        "Ação Irreversível": "Irreversible Action",
        "Tem certeza que deseja excluir esta tarefa? todos os registros de tempo serão mantidos, mas a associação com a task será removida.": "Are you sure you want to delete this task? All time entries will be kept, but the association with the task will be removed.",

        // History Page / HistoryTable
        "Histórico de Ajustes": "Adjustment History",
        "Mês": "Month",
        "Semana": "Week",
        "Dia": "Day",
        "Projeto": "Project",
        "Tarefa": "Task",
        "Duração": "Duration",
        "Data": "Date",
        "Notas": "Notes",
        "Ações": "Actions",
        "Ações de Bloco": "Bulk Actions",
        "Limpar Filtros": "Clear Filters",
        "Filtros Ativos": "Active Filters",
        "Nenhum registro de tempo cadastrado para o período selecionado.": "No time entries registered for the is-selected period.",
        "Sem Notas": "No Notes",
        "Confirmar a exclusão destas entradas de tempo?": "Confirm deletion of these time entries?",
        "Confirmar": "Confirm",
        "Total:": "Total:",
        "Tarefa Excluída": "Deleted Task",
        "Recolher registros": "Collapse entries",
        "Expandir registros": "Expand entries",
        "Editar": "Edit",
        "Editar Grupo/Task": "Edit Group/Task",

        // Profile Page
        "Meu Perfil": "My Profile",
        "Informações Pessoais": "Personal Information",
        "Nome Completo": "Full Name",
        "Email": "Email",
        "Celular": "Mobile phone",
        "País": "Country",
        "Idioma Principal": "Primary Language",
        "Cidade / Província": "City / State",
        "Salvar Alterações": "Save Changes",
        "Segurança da Conta": "Account Security",
        "Senha Atual": "Current Password",
        "Nova Senha": "New Password",
        "Confirmar Nova Senha": "Confirm New Password",
        "Alterar Senha": "Change Password",
        "Salvar": "Save",
        "Salvo com sucesso!": "Saved successfully!",
        "Erro ao salvar. Verifique os campos.": "Error saving. Check fields.",
        "A senha deve conter:": "Password must contain:",
        "Mínimo 8 caracteres": "Minimum 8 characters",
        "Letra maiúscula": "Uppercase letter",
        "Letra minúscula": "Lowercase letter",
        "Número": "Number",
        "Caractere especial": "Special character",

        // Support Page
        "Suporte & Ajuda": "Support & Help",
        "Central de Ajuda": "Help Center",
        "Como podemos ajudar você hoje?": "How can we help you today?",
        "Pesquisar tópicos de ajuda...": "Search help topics...",
        "Envie uma Mensagem": "Send a Message",
        "Descreva o problema ou dúvida": "Describe the problem or question",
        "Assunto": "Subject",
        "Mensagem": "Message",
        "Enviar Mensagem": "Send Message",
        "Sua mensagem foi enviada! Responderemos em breve no seu e-mail cadastrado.": "Your message has been sent! We will reply shortly to your registered email.",
        "Dúvidas Frequentes": "Frequently Asked Questions",

        // Admin Dashboard / Support details
        "Painel de Gerenciamento": "Management Panel",
        "Gerenciar Usuários": "Manage Users",
        "Configurações Gerais": "General Settings",
        "Chamados de Suporte": "Support Tickets",
        "Usuários Registrados": "Registered Users",
        "Total Horas Cronometradas": "Total Tracked Hours",
        "Novos Usuários (Hoje)": "New Users (Today)",
        "Status do Sistema": "System Status",
        "Ativo": "Active",
        "Inativo": "Inactive",
        "Ações de Administrador": "Administrator Actions",
        "Criar Usuário de Teste / Dev": "Create Test / Dev User",
        "Nome": "Name",
        "Criar": "Create",
        "Senha Administrador": "Admin Password",
        "Usuário criado com sucesso!": "User created successfully!",

        // Calendar
        "Calendário de Atividades": "Activity Calendar",
        "Domingo": "Sunday",
        "Segunda": "Monday",
        "Terça": "Tuesday",
        "Quarta": "Wednesday",
        "Quinta": "Thursday",
        "Sexta": "Friday",
        "Sábado": "Saturday",
        "Segunda-feira": "Monday",
        "Terça-feira": "Tuesday",
        "Quarta-feira": "Wednesday",
        "Quinta-feira": "Thursday",
        "Sexta-feira": "Friday",
        "Dom": "Sun",
        "Seg": "Mon",
        "Ter": "Tue",
        "Qua": "Wed",
        "Qui": "Thu",
        "Sex": "Fri",
        "Sáb": "Sat",
        "Janeiro": "January",
        "Fevereiro": "February",
        "Março": "March",
        "Abril": "April",
        "Maio": "May",
        "Junho": "June",
        "Julho": "July",
        "Agosto": "August",
        "Setembro": "September",
        "Outubro": "October",
        "Novembro": "November",
        "Dezembro": "December",

        // Toast etc
        "Cronômetro iniciado": "Timer started",
        "Cronômetro parado": "Timer stopped",
        "Erro ao iniciar cronômetro": "Error starting timer",
        "Erro ao parar cronômetro": "Error stopping timer",

        // History / Billing / Profile additions
        "Total": "Total",
        "Editar Grupo/Tarefa": "Edit Group/Task",
        "Histórico de Sessões": "Session History",
        "Todos": "All",
        "Registros": "Entries",
        "Faturamento": "Billing",
        "Nenhum registro encontrado": "No entries found",
        "Você ainda não cronometrou nenhuma atividade. Vá para a aba Timer!": "You haven't tracked any activity yet. Go to the Timer tab!",
        "Nenhum registro na categoria {category} ainda.": "No entries in {category} category yet.",
        "Todas as Semanas": "All Weeks",
        "Dia da Semana": "Day of the Week",
        "Todos da Semana": "All Week",
        "Nenhum registro no período ou dia selecionado.": "No entries logged for the is-selected period or day.",
        "Editar Registro": "Edit Entry",
        "Data (Resumo)": "Date (Summary)",
        "Horas Trabalhadas (Decimal)": "Worked Hours (Decimal)",
        "Duração (HH:MM:SS)": "Duration (HH:MM:SS)",
        "Erro": "Error",
        "Erro ao salvar": "Error saving",
        "Faturamento & Câmbio de Moedas": "Billing & Currency Exchange",
        "Mostrar Total em": "Show Total in",
        "Atualizando cotação...": "Updating rates...",
        "Câmbio": "Exchange",
        "Nenhum registro para calcular valores.": "No entries to calculate billing values.",
        "Horas Trabalhadas": "Hours Worked",
        "Saldo da Tarefa": "Task Balance",
        "Editar Horas e Valor/Hora": "Edit Hours and Hourly Rate",
        "Total Geral": "Grand Total",
        "O perfil não está disponível no Modo Visitante.": "Profile is not available in Guest Mode.",
        "Cadastre-se para personalizar sua experiência e salvar seus dados na nuvem!": "Register to customize your experience and save your data in the cloud!",
        "Foto e identidade": "Photo and Identity",
        "Trocar foto": "Change Photo",
        "Clique para trocar a foto": "Click to change photo",
        "Nome completo": "Full Name",
        "Seu nome completo": "Your full name",
        "País de origem": "Country of Origin",
        "Buscar país…": "Search country...",
        "Telefone / WhatsApp": "Phone / WhatsApp",
        "Salvando…": "Saving...",
        "Salvar perfil": "Save Profile",
        "Nova senha segura": "Secure new password",
        "Repita a nova senha": "Repeat new password",
        "Alterando…": "Changing...",
        "Perfil salvo com sucesso!": "Profile saved successfully!",
        "Erro ao salvar: ": "Error saving: ",
        "As senhas não coincidem": "Passwords do not match",
        "Senha alterada com sucesso!": "Password changed successfully!",

        // UserWidget
        "Painel Admin": "Admin Panel",
        "Perfil": "Profile",
        "Menu do usuário": "User menu",

        // TimerPage
        "Registros de Hoje": "Today's Entries",
        "Carregando registros de hoje...": "Loading today's entries...",
        "Nenhum registro cronometrado hoje. Escolha uma tarefa ao lado e inicie o cronômetro!": "No entries tracked today. Choose a task and start the timer!",
        "Selecione uma Task abaixo para começar...": "Select a Task below to begin...",
        "Nenhuma Task selecionada": "No Task is-selected",
        "Iniciar": "Start",
        "Pausar": "Pause",
        "Resetar": "Reset",
        "Salvar Registro": "Save Entry",
        "Salvar": "Save",

        // DashboardOverview
        "Todas as categorias": "All categories",
        "Filtros": "Filters",
        "Total acumulado": "Accumulated total",
        "Ano": "Year",
        "Tempo Total Acumulado": "Total Accumulated Time",
        "Proporção por categoria": "Proportion by category",
        "Horas trabalhadas": "Hours worked",
        "Tempo gasto por task": "Time spent per task",

        // CalendarBoard / CalendarPage
        "Calendário de Compromissos": "Appointments Calendar",
        "Hoje": "Today",
        "Mês anterior": "Previous month",
        "Próximo mês": "Next month",
        "Adicionar status/compromisso neste dia": "Add status/appointment on this day",

        // DeadlineModal
        "Editar Compromisso": "Edit Appointment",
        "Novo Compromisso": "New Appointment",
        "Selecione um projeto...": "Select a project...",
        "Tarefa (Opcional)": "Task (Optional)",
        "Nenhuma task (Aplicar ao Projeto)": "No task (Apply to Project)",
        "Data Agendada": "Scheduled Date",
        "Observações": "Notes",
        "Observações sobre o compromisso...": "Notes about the appointment...",
        "Histórico de Alterações de Prazo": "Deadline Change History",
        "Nenhuma alteração de prazo registrada ainda.": "No deadline changes recorded yet.",
        "Remover Compromisso": "Remove Appointment",
        "Salvando...": "Saving...",

        // TaskManagerBoard — category form
        "GERENCIAR CATEGORIA": "MANAGE CATEGORY",
        "Selecionar categoria...": "Select category...",
        "MOEDA": "CURRENCY",
        "Ex.: Trabalho, Freelance, Pessoal...": "E.g.: Work, Freelance, Personal...",
        "New Category": "New Category",
        "+ Create Category": "+ Create Category",

        // Admin panel — AdminDashboardPage
        "Dashboard de Sistema": "System Dashboard",
        "Estatísticas holísticas de engajamento do Trackerígena.": "Holistic engagement statistics of Trackerígena.",
        "Carregando painel geral...": "Loading dashboard...",
        "Projetos ativos": "Active projects",
        "Tarefas cadastradas": "Registered tasks",
        "Horas totais": "Total hours",
        "Resumo": "Summary",
        "O aplicativo possui um volume constante de novos blocos faturados. Utilize o Google Analytics para visualizar o tráfego detalhado em tempo real.": "The application has a steady volume of new billed blocks. Use Google Analytics to view detailed real-time traffic.",

        // Admin panel — UsersManagementPage
        "Gerenciamento de Usuários": "User Management",
        "+ Criar Novo Usuário": "+ Create New User",
        "Usuário": "User",
        "Nome Completo": "Full Name",
        "Telefone": "Phone",
        "Status": "Status",
        "Papel": "Role",
        "Ações": "Actions",
        "Carregando usuários...": "Loading users...",
        "Ativo": "Active",
        "Pendente": "Pending",
        "Membro": "Member",
        "Editar": "Edit",
        "Remover Admin": "Remove Admin",
        "Dar Admin": "Grant Admin",
        "Excluir": "Delete",
        "Nenhum usuário encontrado": "No users found",
        "Deseja remover acesso de administrador para este usuário?": "Remove admin access for this user?",
        "Deseja conceder acesso de administrador para este usuário?": "Grant admin access to this user?",
        "Excluir este usuário APAGARÁ TODOS OS DADOS dele permanentemente. Tem certeza absoluta?": "Deleting this user will PERMANENTLY DELETE ALL THEIR DATA. Are you absolutely sure?",

        // Admin panel — AdminEditUserModal
        "Editar Perfil de": "Edit Profile of",
        "País": "Country",
        "⚠️ Para a segurança do usuário, senhas não podem ser editadas pelo administrador.": "⚠️ For user security, passwords cannot be edited by the administrator.",
        "Salvar Alterações": "Save Changes",

        // Admin panel — AdminCreateUserModal
        "Criar Usuário de Teste / Fake": "Create Test / Fake User",
        "O usuário gerado será ativado instantaneamente e poderá logar no sistema.": "The generated user will be instantly activated and can log in.",
        "Nome de Usuário (Username)": "Username",
        "Email de Teste (Opcional)": "Test Email (Optional)",
        "Deixe em branco para gerar aleatório": "Leave blank to auto-generate",
        "Senha Padrão (Opcional)": "Default Password (Optional)",
        "Deixe em branco para usar: 123456": "Leave blank to use: 123456",
        "Garantir acesso de Administrador?": "Grant Administrator access?",
        "Criando...": "Creating...",
        "Criar e Ativar Usuário": "Create and Activate User",

        // Admin panel — AdminSupportPage
        "Gestão de Helpdesk (Admin)": "Helpdesk Management (Admin)",
        "Responda aos usuários e gerencie o pipeline de suporte.": "Reply to users and manage the support pipeline.",
        "Novos Chamados": "New Tickets",
        "Em Andamento": "In Progress",
        "Resolvidos": "Resolved",
        "Carregando...": "Loading...",
        "Nenhuma fila encontrada para este filtro.": "No queue found for this filter.",
        "Novo / Aguardando Admin": "New / Awaiting Admin",
        "Respondido": "Replied",
        "Resolvido": "Resolved",
        "Monitorando histórico...": "Loading history...",
        "⬅ Voltar": "⬅ Back",
        "✓ Marcar Resolvido": "✓ Mark Resolved",
        "↺ Reabrir Chamado": "↺ Reopen Ticket",
        "🗑️ Excluir": "🗑️ Delete",
        "🔒 Este chamado está resolvido. Os usuários não podem responder até que você reabra.": "🔒 This ticket is resolved. Users cannot reply until you reopen it.",
        "Enviar Resposta": "Send Reply",

        // Admin panel — AdminSettingsPage
        "Configurações Base": "Base Settings",
        "Controle configurações globais, comunicação e bloqueios do sistema.": "Control global settings, communications and system locks.",
        "Banners de Comunicação": "Communication Banners",
        "Carregando configurações...": "Loading settings...",
        "Digite uma mensagem para exibir no topo de todas as telas (avisos, novidades, etc). Deixe em branco para esconder o banner.": "Type a message to display at the top of all screens (notices, updates, etc). Leave blank to hide the banner.",
        "Modo de Manutenção": "Maintenance Mode",
        "Ao ativar, todos os usuários sem nível de Admin não conseguirão navegar pelo aplicativo, e verão uma página de Manutenção. Use com cuidado.": "When enabled, all non-Admin users will be unable to navigate the app and will see a Maintenance page. Use with care.",
        "Aplicar Configurações": "Apply Settings",
        "Configurações salvas e aplicadas em tempo real!": "Settings saved and applied in real time!",
        "Moeda": "Currency",
        "Alterar senha": "Change Password",
        "Senha atual": "Current Password",
        "Nova senha": "New Password",
        "Confirmar nova senha": "Confirm New Password",
        "Dashboard Geral": "General Dashboard",
        "Helpdesk / Suporte": "Helpdesk / Support",
        "⬅ Voltar ao App": "⬅ Back to App",
        "Painel Admin": "Admin Panel",
        "Logs do Sistema": "System Logs",
        "Monitore as ações dos usuários e alterações administrativas em tempo real.": "Monitor user actions and administrative changes in real time.",
        "Todas as Ações": "All Actions",
        "Buscar": "Search",
        "Exibir": "Show",
        "Nome de usuário": "Username",
        "Data e Hora": "Timestamp",
        "Ação": "Action",
        "IP": "IP Address",
        "Descrição": "Description",
        "Sem logs correspondentes aos filtros.": "No logs matching current filters found."
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'pt');

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language === 'en' ? 'en' : 'pt-BR';
    }, [language]);

    const t = (key) => {
        if (language === 'pt') return key;
        const translations = dictionary[language];
        if (translations && translations[key] !== undefined) {
            return translations[key];
        }
        return key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
